//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.GateIn.Console.UI.GateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GateService.GateServicesSoap")]
    public interface GateServicesSoap {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ITI.GateIn.Console.UI.GateService.LoginResponse Login(ITI.GateIn.Console.UI.GateService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.LoginResponse> LoginAsync(ITI.GateIn.Console.UI.GateService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name CheckKendaraanResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckKendaraan", ReplyAction="*")]
        ITI.GateIn.Console.UI.GateService.CheckKendaraanResponse CheckKendaraan(ITI.GateIn.Console.UI.GateService.CheckKendaraanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckKendaraan", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.CheckKendaraanResponse> CheckKendaraanAsync(ITI.GateIn.Console.UI.GateService.CheckKendaraanRequest request);
        
        // CODEGEN: Generating message contract since element name location from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContCardGateIn", ReplyAction="*")]
        ITI.GateIn.Console.UI.GateService.UpdateContCardGateInResponse UpdateContCardGateIn(ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContCardGateIn", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContCardGateInResponse> UpdateContCardGateInAsync(ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequest request);
        
        // CODEGEN: Generating message contract since element name location from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContInOutGateIn", ReplyAction="*")]
        ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInResponse UpdateContInOutGateIn(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContInOutGateIn", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInResponse> UpdateContInOutGateInAsync(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequest request);
        
        // CODEGEN: Generating message contract since element name location from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContCardGateOut", ReplyAction="*")]
        ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutResponse UpdateContCardGateOut(ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContCardGateOut", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutResponse> UpdateContCardGateOutAsync(ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequest request);
        
        // CODEGEN: Generating message contract since element name location from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContInOutGateOut", ReplyAction="*")]
        ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutResponse UpdateContInOutGateOut(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContInOutGateOut", ReplyAction="*")]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutResponse> UpdateContInOutGateOutAsync(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ITI.GateIn.Console.UI.GateService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ITI.GateIn.Console.UI.GateService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckKendaraanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckKendaraan", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.CheckKendaraanRequestBody Body;
        
        public CheckKendaraanRequest() {
        }
        
        public CheckKendaraanRequest(ITI.GateIn.Console.UI.GateService.CheckKendaraanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckKendaraanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public CheckKendaraanRequestBody() {
        }
        
        public CheckKendaraanRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckKendaraanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckKendaraanResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.CheckKendaraanResponseBody Body;
        
        public CheckKendaraanResponse() {
        }
        
        public CheckKendaraanResponse(ITI.GateIn.Console.UI.GateService.CheckKendaraanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckKendaraanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckKendaraanResult;
        
        public CheckKendaraanResponseBody() {
        }
        
        public CheckKendaraanResponseBody(string CheckKendaraanResult) {
            this.CheckKendaraanResult = CheckKendaraanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContCardGateInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContCardGateIn", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequestBody Body;
        
        public UpdateContCardGateInRequest() {
        }
        
        public UpdateContCardGateInRequest(ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContCardGateInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string location;
        
        public UpdateContCardGateInRequestBody() {
        }
        
        public UpdateContCardGateInRequestBody(long id, string location) {
            this.id = id;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContCardGateInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContCardGateInResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.UpdateContCardGateInResponseBody Body;
        
        public UpdateContCardGateInResponse() {
        }
        
        public UpdateContCardGateInResponse(ITI.GateIn.Console.UI.GateService.UpdateContCardGateInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContCardGateInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateContCardGateInResult;
        
        public UpdateContCardGateInResponseBody() {
        }
        
        public UpdateContCardGateInResponseBody(bool UpdateContCardGateInResult) {
            this.UpdateContCardGateInResult = UpdateContCardGateInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContInOutGateInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContInOutGateIn", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequestBody Body;
        
        public UpdateContInOutGateInRequest() {
        }
        
        public UpdateContInOutGateInRequest(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContInOutGateInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string location;
        
        public UpdateContInOutGateInRequestBody() {
        }
        
        public UpdateContInOutGateInRequestBody(long id, string location) {
            this.id = id;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContInOutGateInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContInOutGateInResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInResponseBody Body;
        
        public UpdateContInOutGateInResponse() {
        }
        
        public UpdateContInOutGateInResponse(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContInOutGateInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateContInOutGateInResult;
        
        public UpdateContInOutGateInResponseBody() {
        }
        
        public UpdateContInOutGateInResponseBody(bool UpdateContInOutGateInResult) {
            this.UpdateContInOutGateInResult = UpdateContInOutGateInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContCardGateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContCardGateOut", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequestBody Body;
        
        public UpdateContCardGateOutRequest() {
        }
        
        public UpdateContCardGateOutRequest(ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContCardGateOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string location;
        
        public UpdateContCardGateOutRequestBody() {
        }
        
        public UpdateContCardGateOutRequestBody(long id, string location) {
            this.id = id;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContCardGateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContCardGateOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutResponseBody Body;
        
        public UpdateContCardGateOutResponse() {
        }
        
        public UpdateContCardGateOutResponse(ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContCardGateOutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateContCardGateOutResult;
        
        public UpdateContCardGateOutResponseBody() {
        }
        
        public UpdateContCardGateOutResponseBody(bool UpdateContCardGateOutResult) {
            this.UpdateContCardGateOutResult = UpdateContCardGateOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContInOutGateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContInOutGateOut", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequestBody Body;
        
        public UpdateContInOutGateOutRequest() {
        }
        
        public UpdateContInOutGateOutRequest(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContInOutGateOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string location;
        
        public UpdateContInOutGateOutRequestBody() {
        }
        
        public UpdateContInOutGateOutRequestBody(long id, string location) {
            this.id = id;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContInOutGateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContInOutGateOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutResponseBody Body;
        
        public UpdateContInOutGateOutResponse() {
        }
        
        public UpdateContInOutGateOutResponse(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContInOutGateOutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateContInOutGateOutResult;
        
        public UpdateContInOutGateOutResponseBody() {
        }
        
        public UpdateContInOutGateOutResponseBody(bool UpdateContInOutGateOutResult) {
            this.UpdateContInOutGateOutResult = UpdateContInOutGateOutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GateServicesSoapChannel : ITI.GateIn.Console.UI.GateService.GateServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GateServicesSoapClient : System.ServiceModel.ClientBase<ITI.GateIn.Console.UI.GateService.GateServicesSoap>, ITI.GateIn.Console.UI.GateService.GateServicesSoap {
        
        public GateServicesSoapClient() {
        }
        
        public GateServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GateServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.GateIn.Console.UI.GateService.LoginResponse ITI.GateIn.Console.UI.GateService.GateServicesSoap.Login(ITI.GateIn.Console.UI.GateService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string userId, string password) {
            ITI.GateIn.Console.UI.GateService.LoginRequest inValue = new ITI.GateIn.Console.UI.GateService.LoginRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.LoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            ITI.GateIn.Console.UI.GateService.LoginResponse retVal = ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.LoginResponse> ITI.GateIn.Console.UI.GateService.GateServicesSoap.LoginAsync(ITI.GateIn.Console.UI.GateService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.LoginResponse> LoginAsync(string userId, string password) {
            ITI.GateIn.Console.UI.GateService.LoginRequest inValue = new ITI.GateIn.Console.UI.GateService.LoginRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.LoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.GateIn.Console.UI.GateService.CheckKendaraanResponse ITI.GateIn.Console.UI.GateService.GateServicesSoap.CheckKendaraan(ITI.GateIn.Console.UI.GateService.CheckKendaraanRequest request) {
            return base.Channel.CheckKendaraan(request);
        }
        
        public string CheckKendaraan(long id) {
            ITI.GateIn.Console.UI.GateService.CheckKendaraanRequest inValue = new ITI.GateIn.Console.UI.GateService.CheckKendaraanRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.CheckKendaraanRequestBody();
            inValue.Body.id = id;
            ITI.GateIn.Console.UI.GateService.CheckKendaraanResponse retVal = ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).CheckKendaraan(inValue);
            return retVal.Body.CheckKendaraanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.CheckKendaraanResponse> ITI.GateIn.Console.UI.GateService.GateServicesSoap.CheckKendaraanAsync(ITI.GateIn.Console.UI.GateService.CheckKendaraanRequest request) {
            return base.Channel.CheckKendaraanAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.CheckKendaraanResponse> CheckKendaraanAsync(long id) {
            ITI.GateIn.Console.UI.GateService.CheckKendaraanRequest inValue = new ITI.GateIn.Console.UI.GateService.CheckKendaraanRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.CheckKendaraanRequestBody();
            inValue.Body.id = id;
            return ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).CheckKendaraanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.GateIn.Console.UI.GateService.UpdateContCardGateInResponse ITI.GateIn.Console.UI.GateService.GateServicesSoap.UpdateContCardGateIn(ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequest request) {
            return base.Channel.UpdateContCardGateIn(request);
        }
        
        public bool UpdateContCardGateIn(long id, string location) {
            ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequest inValue = new ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequestBody();
            inValue.Body.id = id;
            inValue.Body.location = location;
            ITI.GateIn.Console.UI.GateService.UpdateContCardGateInResponse retVal = ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).UpdateContCardGateIn(inValue);
            return retVal.Body.UpdateContCardGateInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContCardGateInResponse> ITI.GateIn.Console.UI.GateService.GateServicesSoap.UpdateContCardGateInAsync(ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequest request) {
            return base.Channel.UpdateContCardGateInAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContCardGateInResponse> UpdateContCardGateInAsync(long id, string location) {
            ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequest inValue = new ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.UpdateContCardGateInRequestBody();
            inValue.Body.id = id;
            inValue.Body.location = location;
            return ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).UpdateContCardGateInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInResponse ITI.GateIn.Console.UI.GateService.GateServicesSoap.UpdateContInOutGateIn(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequest request) {
            return base.Channel.UpdateContInOutGateIn(request);
        }
        
        public bool UpdateContInOutGateIn(long id, string location) {
            ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequest inValue = new ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequestBody();
            inValue.Body.id = id;
            inValue.Body.location = location;
            ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInResponse retVal = ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).UpdateContInOutGateIn(inValue);
            return retVal.Body.UpdateContInOutGateInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInResponse> ITI.GateIn.Console.UI.GateService.GateServicesSoap.UpdateContInOutGateInAsync(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequest request) {
            return base.Channel.UpdateContInOutGateInAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInResponse> UpdateContInOutGateInAsync(long id, string location) {
            ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequest inValue = new ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.UpdateContInOutGateInRequestBody();
            inValue.Body.id = id;
            inValue.Body.location = location;
            return ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).UpdateContInOutGateInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutResponse ITI.GateIn.Console.UI.GateService.GateServicesSoap.UpdateContCardGateOut(ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequest request) {
            return base.Channel.UpdateContCardGateOut(request);
        }
        
        public bool UpdateContCardGateOut(long id, string location) {
            ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequest inValue = new ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequestBody();
            inValue.Body.id = id;
            inValue.Body.location = location;
            ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutResponse retVal = ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).UpdateContCardGateOut(inValue);
            return retVal.Body.UpdateContCardGateOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutResponse> ITI.GateIn.Console.UI.GateService.GateServicesSoap.UpdateContCardGateOutAsync(ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequest request) {
            return base.Channel.UpdateContCardGateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutResponse> UpdateContCardGateOutAsync(long id, string location) {
            ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequest inValue = new ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.UpdateContCardGateOutRequestBody();
            inValue.Body.id = id;
            inValue.Body.location = location;
            return ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).UpdateContCardGateOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutResponse ITI.GateIn.Console.UI.GateService.GateServicesSoap.UpdateContInOutGateOut(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequest request) {
            return base.Channel.UpdateContInOutGateOut(request);
        }
        
        public bool UpdateContInOutGateOut(long id, string location) {
            ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequest inValue = new ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequestBody();
            inValue.Body.id = id;
            inValue.Body.location = location;
            ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutResponse retVal = ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).UpdateContInOutGateOut(inValue);
            return retVal.Body.UpdateContInOutGateOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutResponse> ITI.GateIn.Console.UI.GateService.GateServicesSoap.UpdateContInOutGateOutAsync(ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequest request) {
            return base.Channel.UpdateContInOutGateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutResponse> UpdateContInOutGateOutAsync(long id, string location) {
            ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequest inValue = new ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequest();
            inValue.Body = new ITI.GateIn.Console.UI.GateService.UpdateContInOutGateOutRequestBody();
            inValue.Body.id = id;
            inValue.Body.location = location;
            return ((ITI.GateIn.Console.UI.GateService.GateServicesSoap)(this)).UpdateContInOutGateOutAsync(inValue);
        }
    }
}
